swagger: '2.0'
info:
  title: Songs_MS
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /getSongs:
    get:
      tags: [GetSongs]
      operationId: Business.get_user_songs
      responses:
        200:
          description: OK
  /getSong:
    get:
      tags: [GetSongs]
      operationId: Business.get_song
      parameters:
        - name: song_id
          in: query
          type: integer
          description: Get information about a specific song.
      responses:
        200:
          description: OK
  /getSongsCriteria:
    get:
      tags: [GetSongsCriteria]
      operationId: Business.get_songs_criteria
      parameters:
        - name: title
          in: query
          type: string
          description: Song title.
        - name: artist
          in: query
          type: string
          description: Song artist.
      responses:
        200:
          description: OK
  /putSong:
    put:
      tags: [GetSongs]
      consumes:
        - application/x-www-form-urlencoded
      operationId: Business.put_song
      parameters:
        - in: formData
          name: title
          type: string
          description: Title of the song.
        - in: formData
          name: artist
          type: string
          description: Artist name.
        - in: formData
          name: album
          type: string
          description: Album name.
        - in: formData
          name: release_year
          type: integer
          description: Year of the song release.
        - in: formData
          name: path_song
          type: string
          description: Path for the song file.
        - in: formData
          name: song_id
          type: integer
          description: Song ID.
      responses:
        200:
          description: OK
  /createSong:
    post:
      summary: Create Song
      consumes:
        - application/x-www-form-urlencoded
      operationId: Business.post_song
      parameters:
        - in: formData
          name: title
          type: string
          description: Title of the song.
        - in: formData
          name: artist
          type: string
          description: Artist name.
        - in: formData
          name: album
          type: string
          description: Album name.
        - in: formData
          name: release_year
          type: integer
          description: Year of the song release.
        - in: formData
          name: path_song
          type: string
          description: Path for the song file.
      responses:
        200:
          description: OK
  /getPlaylistSongs:
    get:
      tags: [GetSongs]
      operationId: Business.get_playlist_songs
      parameters:
        - name: songs
          in: query
          type: array
          items:
            type: string
          description: Get information about a specific song.
      responses:
        200:
          description: OK
  /delSong:
    post:
      summary: Delete Song
      consumes:
        - application/x-www-form-urlencoded
      operationId: Business.del_song
      parameters:
        - in: formData
          name: song_id
          type: integer
          description: ID of the song.
      responses:
        200:
          description: OK
  /delUserSongs:
    post:
      summary: Delete User Songs
      consumes:
        - application/x-www-form-urlencoded
      operationId: Business.del_user_songs
      parameters:
        - in: formData
          name: admin_id
          type: integer
          description: ID of admin user.
      responses:
        200:
          description: OK