version: "3"
services:
  eureka:
    image: eureka-server
    expose:
      - "8761"
  zuul:
    image: zuul-gateway
    expose:
      - "4000"
    environment:
      - LOGSERVERADDRESS=10.0.2.15:4040
      - EUREKA=eureka:8761
  ms-db:
    image: mariadb
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ribeiro
  users:
    image: users-ms
    expose:
      - "5000"
    links:
      - ms-db
    environment:
      - DATABASEADDRESS=ms-db:3306
      - EUREKA_SERVICE_URL=eureka:8761
      - EUREKA_INSTANCE_PORT=5000
  songs:
    image: songs-ms
    expose:
      - "5001"
    links:
      - ms-db
    environment:
      - DATABASEADDRESS=ms-db:3306
      - EUREKA_SERVICE_URL=eureka:8761
      - EUREKA_INSTANCE_PORT=5001
  playlists:
    image: playlists-ms
    expose:
      - "5002"
    links:
      - ms-db
      - songs
    environment:
      - DATABASEADDRESS=ms-db:3306
      - SONGSADDRESS=songs:4000/songs-ms
      - EUREKA_SERVICE_URL=eureka:8761
      - EUREKA_INSTANCE_PORT=5002
  auth:
    image: auth-ms
    expose:
      - "5003"
    links:
      - users
    environment:
      - USERSADDRESS=users:4000/users-ms
      - EUREKA_SERVICE_URL=eureka:8761
      - EUREKA_INSTANCE_PORT=5003
  aggr:
    image: aggr-ms
    expose:
      - "5004"
    links:
      - users
      - playlists
      - songs
      - auth
    environment:
      - USERSADDRESS=users:4000/users-ms
      - PLAYLISTSADDRESS=playlists:4000/playlists-ms
      - SONGSADDRESS=songs:4000/songs-ms
      - AUTHADDRESS=auth:4000/auth-ms
      - EUREKA_SERVICE_URL=eureka:8761
      - EUREKA_INSTANCE_PORT=5004

