version: "3"
services:
  ms_db:
    # replace username/repo:tag with your name and image details
    image: mariadb
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ribeiro
  users_ms:
    # replace username/repo:tag with your name and image details
    image: fabiopina151/users_ms
    expose:
      - "5000"
    links:
      - ms_db
    environment:
      - DATABASEADDRESS=ms_db:3306
  songs_ms:
    # replace username/repo:tag with your name and image details
    image: fabiopina151/songs_ms
    expose:
      - "5001"
    links:
      - ms_db
    environment:
      - DATABASEADDRESS=ms_db:3306
  playlists_ms:
    # replace username/repo:tag with your name and image details
    image: fabiopina151/playlists_ms
    expose:
      - "5002"
    links:
      - ms_db
    environment:
      - DATABASEADDRESS=ms_db:3306
  authentication_ms:
    # replace username/repo:tag with your name and image details
    image: fabiopina151/auth_ms
    expose:
      - "5003"
    links:
      - users_ms
    environment:
      - USERSADDRESS=10.0.2.15:4000/users


