version: "3"
services:
  eureka:
    image: eureka-server
    expose:
      - "8761"
    environment:
      - PORT=8761
  zuul:
    image: zuul-gateway
    expose:
      - "4000"
    environment:
      - PORT=4000
      - LOGSERVERADDRESS=10.0.2.15:4040
      - EUREKA=eureka:8761
