version: "3"
services:
  main_app:
    image: fcribeiro/main_app
    expose:
      - "8080"
    links:
      - users_ms
      - songs_ms
      - playlists_ms
    environment:
      - USERSADDRESS=users_ms:5000
      - SONGSADDRESS=songs_ms:5001
      - PLAYLISTSADDRESS=playlists_ms:5002
  users_ms:
    image: fcribeiro/users_ms
    expose:
      - "5000"
    links:
      - ms_db
    environment:
      - DATABASEADDRESS=ms_db:3306
  songs_ms:
    image: fcribeiro/songs_ms
    expose:
      - "5001"
    links:
      - ms_db
    environment:
      - DATABASEADDRESS=ms_db:3306
  playlists_ms:
    image: fcribeiro/playlists_ms
    expose:
      - "5002"
    links:
      - ms_db
    environment:
      - DATABASEADDRESS=ms_db:3306
  ms_db:
    image: mariadb
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ribeiro


