swagger: '2.0'
info:
  title: Log_Server
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      operationId: application.hello_world
      summary: "Hello World!"
      tags: [Log_Server]
      responses:
        200:
          description: OK
  /log:
    post:
      operationId: application.create_log_entry
      tags: [Log_Server]
      summary: "Creates a log entry"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: '#/definitions/Log'
      responses:
        200:
          description: "OK."
        400:
          description: "Bad request."
        500:
          description: "Internal server error."

definitions:
  Log:
    type: "object"
    required:
    - "status"
    - "message"
    properties:
      status:
        type: "string"
        example: "INCOMING"
        description: "Status"
      message:
        type: "string"
        example: "123456"
        description: "Message"
