swagger: '2.0'
info:
  title: Users_MS
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /login:
    get:
      tags: [GetUser]
      operationId: Business.login
      responses:
        200:
          description: OK