version: "3"
services:
  users_ms:
    # replace username/repo:tag with your name and image details
    image: fcribeiro/users_ms_p3
    expose:
      - "5000"
    links:
      - ms_db
    environment:
      - DATABASEADDRESS=ms_db:3306
  songs_ms:
    # replace username/repo:tag with your name and image details
    image: fcribeiro/songs_ms_p3
    expose:
      - "5001"
    links:
      - ms_db
    environment:
      - DATABASEADDRESS=ms_db:3306
  playlists_ms:
    # replace username/repo:tag with your name and image details
    image: fcribeiro/playlists_ms_p3
    expose:
      - "5002"
    links:
      - ms_db
    environment:
      - DATABASEADDRESS=ms_db:3306
  authentication_ms:
    # replace username/repo:tag with your name and image details
    image: fcribeiro/authentication_ms
    expose:
      - "5003"
    links:
      - users_ms
    environment:
      - USERSADDRESS=users_ms:5000
  ms_db:
    # replace username/repo:tag with your name and image details
    image: mariadb
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ribeiro


