swagger: '2.0'
info:
  title: Spotify
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /getSongs:
    get:
      tags: [GetSongs]
      operationId: Business.get_user_songs
      parameters:
        - name: userID
          in: query
          type: integer
          description: The number of items to skip before starting to collect the result set.
      responses:
        200:
          description: OK
