swagger: '2.0'
info:
  title: Spotify
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /js/{js_page_name}:
    get:
      tags: [Playlists]
      operationId: Business.send_javascript
      produces:
        - application/javascript; charset=utf-8
      summary: Get all playlists
      parameters:
        - $ref: '#/parameters/js_page_name'
      responses:
        200:
          description: OK
  /register:
    get:
      tags: [Register]
      operationId: Business.register
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: OK
    post:
      tags: [Register]
      operationId: Business.post_user
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: OK
        409:
          description: ResourceAlreadyExists
  /searchSongs:
    get:
      tags: [SearchSongs]
      operationId: Business.search_songs
      produces:
        - text/html; charset=utf-8
      summary: SearchSongs
      responses:
        200:
          description: OK
    post:
      tags: [SearchSongs]
      operationId: Business.search_songs_post
      produces:
        - text/html; charset=utf-8
      summary: SearchSongs
      responses:
        200:
          description: OK
  /getSongsCriteria:
    get:
      tags: [GetSongsCriteria]
      operationId: Business.get_songs_criteria
      summary: GetSongsCriteria
      responses:
        200:
          description: OK
  /createPlayList:
    get:
      tags: [CreatePlayListView]
      operationId: Business.create_playlist_view
      produces:
        - text/html; charset=utf-8
      summary: CreatePlayListView
      responses:
        200:
          description: OK
    post:
      tags: [PostPlayList]
      operationId: Business.post_playlist
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: OK
  /createSong:
    get:
      tags: [CreateSong]
      operationId: Business.create_song_view
      produces:
        - text/html; charset=utf-8
      summary: CreateSong
      responses:
        200:
          description: OK
    post:
      tags: [CreateSong]
      operationId: Business.post_song
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: OK
  /myPlayListDel:
    get:
      tags: [MyPlayListDel]
      operationId: Business.delete_playlist
      produces:
        - text/html; charset=utf-8
      summary: MyPlayListDel
      responses:
        200:
          description: OK
  /myPlayLists:
    get:
      tags: [MyPlayLists]
      operationId: Business.my_playlists
      produces:
        - text/html; charset=utf-8
      summary: MyPlayLists
      responses:
        200:
          description: OK
  /myPlayListEdit:
    get:
      tags: [MyPlayListEdit]
      operationId: Business.my_playlist_edit
      produces:
        - text/html; charset=utf-8
      summary: MyPlayListEdit
      responses:
        200:
          description: OK
    post:
      tags: [EditPlayList]
      operationId: Business.put_playlist
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: OK
  /getPlayListInfo:
    get:
      tags: [GETMyPlayList]
      operationId: Business.get_playlist
      summary: GETMyPlayList
      responses:
        200:
          description: OK
  /getPlaylists:
    get:
      tags: [GetPlaylists]
      operationId: Business.get_user_playlists
      summary: Get user playlists
      responses:
        200:
          description: OK
  /getSongs:
    get:
      tags: [GetSongs]
      operationId: Business.get_user_songs
      summary: Get user songs
      responses:
        200:
          description: OK
  /getSongInfo:
    get:
      tags: [GETMySong]
      operationId: Business.get_song
      summary: GETMySong
      responses:
        200:
          description: OK
  /getPlaylistSongs:
    get:
      tags: [GetPlaylistSongs]
      operationId: Business.get_playlist_songs
      summary: Get user Playlist songs
      responses:
        200:
          description: OK
  /getUser:
    get:
      tags: [GetUser]
      operationId: Business.get_user
      summary: Get user
      responses:
        200:
          description: OK
  /mySongs:
    get:
      tags: [MySongs]
      operationId: Business.my_songs
      produces:
        - text/html; charset=utf-8
      summary: MySongs
      responses:
        200:
          description: OK
  /mySongDel:
    get:
      tags: [DeleteSong]
      operationId: Business.delete_song
      produces:
        - text/html; charset=utf-8
      summary: DeleteSong
      responses:
        200:
          description: OK
  /mySongDelete:
    get:
      tags: [DeleteSong]
      operationId: Business.post_remove_song_from_playlist
      produces:
        - text/html; charset=utf-8
      summary: DeleteSong
      responses:
        200:
          description: OK
  /mySongEdit:
    get:
      tags: [EditSong]
      operationId: Business.my_song_edit
      produces:
        - text/html; charset=utf-8
      summary: EditSong
      responses:
        200:
          description: OK
    post:
      tags: [EditSong]
      operationId: Business.put_song
      produces:
        - text/html; charset=utf-8
      summary: EditSong
      responses:
        200:
          description: OK
  /addSongPlayList:
    get:
      tags: [AddSongPlayList]
      operationId: Business.add_song_playlist
      produces:
        - text/html; charset=utf-8
      summary: AddSongPlayList
      responses:
        200:
          description: OK
  /addSongToPlayListFinal:
    get:
      tags: [AddSongToPlayListFinal]
      operationId: Business.post_add_song_into_playlist
      produces:
        - text/html; charset=utf-8
      summary: AddSongToPlayListFinal
      responses:
        200:
          description: OK
  /myPlayListSongs:
    get:
      tags: [MyPlayListSongs]
      operationId: Business.my_playlist_songs
      produces:
        - text/html; charset=utf-8
      summary: MyPlayListSongs
      responses:
        200:
          description: OK
  /editAccountView:
    get:
      tags: [EditAccountView]
      operationId: Business.edit_account_view
      produces:
        - text/html; charset=utf-8
      summary: EditAccountView
      responses:
        200:
          description: OK
    post:
      tags: [EditAccount]
      operationId: Business.put_user
      produces:
        - text/html; charset=utf-8
      summary: EditAccount
      responses:
        200:
          description: OK
  /deleteAccount:
    get:
      tags: [DeleteUser]
      operationId: Business.delete_user
      produces:
        - text/html; charset=utf-8
      summary: DeleteUser
      responses:
        200:
          description: OK
  /logOut:
    get:
      tags: [Logout]
      operationId: Business.logout
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: OK
  /login:
    get:
      tags: [Login]
      operationId: Business.login
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: OK
    post:
      tags: [Login]
      operationId: Business.check_login
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
  /:
    get:
      tags: [Home]
      operationId: Business.home
      produces:
        - text/html; charset=utf-8
      summary: Homepage
      responses:
        200:
          description: OK

parameters:
  js_page_name:
    name: js_page_name
    description: The js page name
    in: path
    type: string
    pattern: "^[a-zA-Z0-9-]*.js$"
    required: true