server:
  port: 4000

zuul:
  routes:
    users:
      serviceId: users-service
      path: /users-ms/**
      url: http://172.18.0.4:5000
      sensitiveHeaders:
    songs:
      serviceId: songs-service
      path: /songs-ms/**
      url: http://172.18.0.3:5001
      sensitiveHeaders:
    playlists:
      serviceId: playlists-service
      path: /playlists-ms/**
      url: http://172.18.0.5:5002
      sensitiveHeaders:
    authentication:
      serviceId: authentication-service
      path: /auth-ms/**
      url: http://172.18.0.6:5003
      sensitiveHeaders:
    aggregator:
      serviceId: aggregator-service
      path: /aggr-ms/**
      url: http://172.18.0.7:5004
      sensitiveHeaders:

ribbon:
  eureka:
    enabled: false