swagger: '2.0'
info:
  title: Users_MS
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /createUser:
    post:
      summary: Create User
      consumes:
        - application/x-www-form-urlencoded
      operationId: Business.post_user
      parameters:
        - in: formData
          name: name
          type: string
          description: User Name.
        - in: formData
          name: email
          type: string
          description: User Email.
        - in: formData
          name: password
          type: string
          description: User Password.
      responses:
        200:
          description: OK
  /getUser:
    get:
      tags: [GetUser]
      operationId: Business.get_user
      parameters:
        - name: user_id
          in: query
          type: integer
          description: Get information about a specific User.
      responses:
        200:
          description: OK
  /putUser:
    put:
      tags: [GetSongs]
      consumes:
        - application/x-www-form-urlencoded
      operationId: Business.put_user
      parameters:
        - in: formData
          name: user_id
          type: integer
          description: User's ID.
        - in: formData
          name: name
          type: string
          description: User's name.
        - in: formData
          name: email
          type: string
          description: User's Email.
        - in: formData
          name: password
          type: string
          description: User's Password.
      responses:
        200:
          description: OK
