server:
  port:
    4000

spring:
  application:
    name: zuul-gateway

zuul:
  prefix: /api
  routes:
    users-ms:
      path: /users-ms/**
      serviceId: USERS-MS
      sensitiveHeaders:
    songs-ms:
      path: /songs-ms/**
      serviceId: SONGS-MS
      sensitiveHeaders:
    playlists-ms:
      path: /playlists-ms/**
      serviceId: PLAYLISTS-MS
      sensitiveHeaders:
    auth-ms:
      path: /auth-ms/**
      serviceId: AUTH-MS
      sensitiveHeaders:
    aggr-ms:
      path: /aggr-ms/**
      serviceId: AGGR-MS
      sensitiveHeaders:


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
