swagger: '2.0'
info:
  title: Aggregator_MS
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      operationId: application.hello_world
      summary: "Hello World!"
      tags: [Aggregator_MS]
      responses:
        200:
          description: OK




